import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { FORMAT_PATTERNS, checkSkillFormat, failedRules, formatPasses, splitFrontmatter } from "./skill-format.js";

/**
 * The verdicts of the measurement harness's checker, dumped by its own fixtures rather than copied
 * by hand: a table typed out from a reading of the script would agree with that reading, not with
 * the script. Regenerated by `dump-fixtures.py` when the source checker changes.
 */
interface Dump {
  denyTerms: string[];
  denyUsers: string[];
  positives: { pattern: string; text: string; matches: boolean }[];
  excludedPositives: { pattern: string; reason: string }[];
  mustPass: { label: string; text: string; rules: Record<string, { ok: boolean; required: boolean }> }[];
  broken: {
    label: string;
    text: string;
    expectedFailed: string[];
    rules: Record<string, { ok: boolean; required: boolean }>;
  }[];
}

const dump: Dump = JSON.parse(readFileSync(join(__dirname, "skill-format-fixtures.json"), "utf8"));
const options = { denyTerms: dump.denyTerms, denyUsers: dump.denyUsers };

describe("agreeing with the checker the baseline was measured with", () => {
  it("given the dumped fixtures, when counted, then the ported suite is present and the rest is named", () => {
    expect(dump.positives).toHaveLength(19);
    expect(dump.mustPass).toHaveLength(3);
    expect(dump.broken).toHaveLength(21);
    expect(dump.positives.length + dump.mustPass.length + dump.broken.length).toBe(43);
    // The source checker also matches phrases in the language its own measurements were written
    // in. Those belong to a measurement tool; this is product code, which the repository keeps in
    // one language. The four fixtures that exercise them are excluded BY NAME, so the narrowing is
    // counted here rather than passing silently or failing without an explanation.
    expect(dump.excludedPositives).toHaveLength(4);
    expect(dump.excludedPositives.map((e) => e.pattern).sort()).toEqual([
      "DELIVERY_HEAD_RE",
      "NUM_HEAD_RE",
      "PITFALL_HEAD_RE",
      "VERIFY_HEAD_RE",
    ]);
  });

  it("given the dumped fixtures, when read as text, then no real machine path shape is carried", () => {
    // Two fixtures must contain an absolute home path, because the rule they test is the one that
    // forbids them. They use the POSIX prefix, which both checkers match through the same
    // alternation, so the rule is still tested and the repository carries nothing shaped like a
    // path from the machine that generated this.
    const raw = readFileSync(join(__dirname, "skill-format-fixtures.json"), "utf8");
    expect(raw).not.toContain(`/${"Users"}/`);
    expect(raw).toContain("/home/");
    expect(failedRules(checkSkillFormat(dump.broken.find((b) => b.label === "no-abs-path")!.text, options)))
      .toContain("no-abs-path");
  });

  it("given a heading in another language, when checked, then it no longer reaches the ported rules", () => {
    // The consequence of the narrowing, pinned so it is a decision rather than a surprise.
    expect(FORMAT_PATTERNS["DELIVERY_HEAD_RE"]!.test("6. Teslim")).toBe(false);
    expect(FORMAT_PATTERNS["DELIVERY_HEAD_RE"]!.test("5. Delivery")).toBe(true);
  });

  describe.each(dump.positives)("regex positive $pattern <- $text", ({ pattern, text, matches }) => {
    it("given the source's own positive, when matched here, then the same pattern still finds it", () => {
      const re = FORMAT_PATTERNS[pattern];
      expect(re, `no ported pattern named ${pattern}`).toBeDefined();
      // A global pattern carries a cursor between calls, which would make this depend on test order.
      const fresh = new RegExp(re!.source, re!.flags.replace("g", ""));
      expect(fresh.test(text)).toBe(matches);
    });
  });

  describe.each(dump.mustPass)("must pass: $label", ({ text, rules }) => {
    it("given a fixture the source accepts, when checked here, then every rule agrees", () => {
      const findings = checkSkillFormat(text, options);
      for (const finding of findings) {
        expect(finding.ok, `${finding.rule}: ${finding.detail}`).toBe(rules[finding.rule]?.ok);
        expect(finding.required, finding.rule).toBe(rules[finding.rule]?.required);
      }
      expect(findings.map((f) => f.rule).sort()).toEqual(Object.keys(rules).sort());
      expect(formatPasses(findings)).toBe(true);
    });
  });

  describe.each(dump.broken)("broken: $label", ({ text, expectedFailed, rules }) => {
    it("given a fixture the source rejects, when checked here, then exactly the same rules fail", () => {
      const findings = checkSkillFormat(text, options);
      for (const finding of findings) {
        expect(finding.ok, `${finding.rule}: ${finding.detail}`).toBe(rules[finding.rule]?.ok);
      }
      // The source counts an optional rule as a failure in its own self-test, so this list is
      // every rule that came back false, not only the required ones.
      const failed = findings.filter((f) => !f.ok).map((f) => f.rule).sort();
      expect(failed).toEqual(expectedFailed);
    });
  });

  it("given every fixture, when the required rules are counted, then thirteen of them are mandatory", () => {
    const findings = checkSkillFormat(dump.mustPass[0]!.text, options);
    expect(findings.filter((f) => f.required).map((f) => f.rule)).toEqual([
      "frontmatter",
      "name",
      "description",
      "listing-cap",
      "trigger",
      "steps",
      "verification",
      "pitfalls",
      "no-abs-path",
      "no-email",
      "no-username",
      "no-org-term",
      "body-length",
    ]);
    expect(findings.filter((f) => !f.required).map((f) => f.rule)).toEqual(["argument-hint"]);
  });
});

/**
 * The three rules the source checker never measured. Applied unconditionally they failed all three
 * of its must-pass fixtures, so each was narrowed; these tests pin both halves of that narrowing -
 * what the rule stopped asking for, and what it still catches.
 */
describe("the rules that cover the parts of the template a mined workflow fills", () => {
  const ext = { ...options, extended: true };

  describe.each(dump.mustPass)("must still pass with the new rules: $label", ({ text }) => {
    it("given a hand-written skill that owes no map, when checked, then the new rules do not fail it", () => {
      expect(failedRules(checkSkillFormat(text, ext))).toEqual([]);
    });
  });

  it("given a draft that owed a file map and has none, when checked, then the map rule fails", () => {
    const text = dump.mustPass[0]!.text;
    expect(failedRules(checkSkillFormat(text, { ...ext, expects: { fileMap: true } }))).toContain("file-map");
  });

  it("given a map whose rows do not say how often, when checked, then the map rule fails", () => {
    const text = dump.mustPass[0]!.text.replace(
      "## Common mistakes (observed)",
      "## 3. File map (6 past changes)\n| File | Touched in |\n|---|---|\n| src/a.ts | often |\n\n## Common mistakes (observed)",
    );
    expect(failedRules(checkSkillFormat(text, ext))).toContain("file-map");
  });

  it("given work across repositories and no delivery section, when checked, then the delivery rule fails", () => {
    const text = dump.mustPass[0]!.text;
    expect(failedRules(checkSkillFormat(text, { ...ext, expects: { multiRepo: true } }))).toContain("delivery");
  });

  it("given a single-repository note, when checked, then the delivery rule is satisfied", () => {
    const text = dump.mustPass[0]!.text.replace(
      "## Common mistakes (observed)",
      "## 5. Delivery\nsingle repo\n\n## Common mistakes (observed)",
    );
    expect(failedRules(checkSkillFormat(text, { ...ext, expects: { multiRepo: true } }))).not.toContain("delivery");
  });

  it("given a check that only says to run the tests, when checked, then it is not concrete enough", () => {
    const text = dump.mustPass[0]!.text.replace("- [ ] Run `npm test`.", "- [ ] Run the tests.");
    expect(failedRules(checkSkillFormat(text, ext))).toContain("verification-concrete");
  });

  it("given a check naming what to look at, when checked, then observing counts as a result", () => {
    const text = dump.mustPass[0]!.text.replace("- [ ] Run `npm test`.", "- [ ] Open the page and see the widget.");
    expect(failedRules(checkSkillFormat(text, ext))).not.toContain("verification-concrete");
  });

  it("given the empty template itself, when checked, then it is rejected", () => {
    const skeleton = dump.broken.find((b) => b.label === "skeleton-empty")!.text;
    expect(failedRules(checkSkillFormat(skeleton, ext)).length).toBeGreaterThan(0);
  });
});

describe("reading the header the way the source reads it", () => {
  it("given a quoted block value, when split, then markers and matching quotes come off", () => {
    const { fields, body } = splitFrontmatter('---\nname: a-b\ndescription: >-\n  one\n  two\n---\nbody\n');
    expect(fields).toEqual({ name: "a-b", description: "one two" });
    expect(body).toBe("body\n");
  });

  it("given no header at all, when split, then the whole file is the body", () => {
    const { fields, body } = splitFrontmatter("# just a title\n");
    expect(fields).toBeNull();
    expect(body).toBe("# just a title\n");
  });
});

/**
 * The divergences between the two regex engines, each measured on the input that exposed it. These
 * are the cases the source's own fixtures cannot reach, because every one of them is ASCII.
 */
describe("keeping the wider Unicode meanings the source engine has", () => {
  const base = dump.mustPass[0]!.text;

  it("given an address with a non-ASCII letter, when checked, then the address rule still catches it", () => {
    const text = base.replace("Run `npm test`.", "Ask someone@soci\u00e9t\u00e9.com.");
    expect(failedRules(checkSkillFormat(text, options))).toContain("no-email");
  });

  it("given a forbidden term with a non-ASCII letter, when checked, then the term rule catches it", () => {
    const term = "soci\u00e9t\u00e9";
    const text = base.replace("Run `npm test`.", `Run the ${term} suite.`);
    expect(failedRules(checkSkillFormat(text, { denyTerms: [term] }))).toContain("no-org-term");
  });

  it("given a term inside a longer word, when checked, then the boundary keeps it from matching", () => {
    const text = base.replace("Run `npm test`.", "Run the acmecorporate suite.");
    expect(failedRules(checkSkillFormat(text, options))).not.toContain("no-org-term");
  });

  it("given a term opening with punctuation, when checked, then a boundary before it demands a word character", () => {
    const text = base.replace("Run `npm test`.", "Ask @jdoe.");
    expect(failedRules(checkSkillFormat(text, { denyUsers: ["@jdoe"] }))).not.toContain("no-username");
  });

  it("given trigger phrases in capitals, when counted, then case is not what decides", () => {
    const text = base.replace(
      /description: .*/,
      'description: Does a thing. USE WHEN a ticket asks. ALSO WHEN it comes back empty.',
    );
    expect(failedRules(checkSkillFormat(text, options))).not.toContain("trigger");
  });

  it("given an abbreviation before a trigger phrase, when sentences are split, then it does not become two", () => {
    const withAbbrev = "Does a thing, e.g. a chart. Use when a ticket asks for one.";
    const findings = checkSkillFormat(base.replace(/description: .*/, `description: ${withAbbrev}`), options);
    // One trigger sentence only: the rule must fail, and it must fail because the count is 1
    // rather than because "e.g." was read as a sentence end and split the text into more.
    expect(findings.find((f) => f.rule === "trigger")!.detail).toContain("sentences=1");
  });

  it("given an astral character in the name, when measured, then the limit counts code points", () => {
    const { fields } = splitFrontmatter(`---\nname: "a\u{1D400}b"\ndescription: x\n---\n`);
    expect([...fields!["name"]!].length).toBe(3);
  });
});

/**
 * A draft shaped the way a mined workflow is supposed to come out: its own fixture rather than a
 * mutation of the hand-written ones, which belong to the equivalence table and are not drafts.
 */
const DRAFT = `---
name: add-widget-route
description: >-
  Adds a widget route across the service and the gateway. Use when a ticket asks for a new widget
  endpoint. Also when a route answers through the service but not through the gateway.
---
# add-widget-route - a new widget route

Two repositories, and the gateway copy is the one people forget.

## 0. Reading the ticket
- Which widget the route is for.

## 1. Service
1. Add the handler in \`controller/WidgetController.kt\`. [map 1]
2. Add the request shape in \`dto/WidgetRequest.kt\`. [map 2]

## 2. Gateway
1. Register the path in \`endpoints/widget_endpoints.json\`. [map 3]
2. Keep the method the same on both sides. [fix 1]

## Not visible in history
- Whether the gateway needs a new rate class is recorded in no commit.

## 3. File map (9 past changes)
| File (pattern) | Touched in | Note |
|---|---|---|
| \`controller/*Controller.kt\` | 9/9 | the handler |
| \`dto/*Request.kt\` | 8/9 | the input shape |
| \`endpoints/*_endpoints.json\` | 7/9 | the gateway route |

## 4. Verification
- [ ] \`./gradlew test\` exits 0.
- [ ] The route returns 200 through the gateway.

## 5. Delivery
- The service merges first, then the gateway.

## Common mistakes (observed)
| Mistake | Evidence | Do instead |
|---|---|---|
| method differs between the two sides | #1 | compare both files |
`;

describe("the rules that read a draft as a structure", () => {
  const citable = { map: 3, fix: 1, hunk: 0, subject: 0 };
  const ext = { ...options, extended: true, expects: { fileMap: true, multiRepo: true, citable } };

  it("given a draft that meets the template, when checked, then nothing fails", () => {
    expect(failedRules(checkSkillFormat(DRAFT, ext))).toEqual([]);
  });

  it("given two sections numbered the same, when checked, then the section rule fails", () => {
    const text = DRAFT.replace("## 3. File map", "## 2. File map");
    expect(failedRules(checkSkillFormat(text, ext))).toContain("unique-sections");
  });

  it("given a map whose first column is a sentence, when checked, then the pattern rule fails", () => {
    const text = DRAFT.replace("| \`dto/*Request.kt\` | 8/9 |", "| the request shape the BFF sends | 8/9 |");
    expect(failedRules(checkSkillFormat(text, ext))).toContain("file-map-pattern");
  });

  it("given a step naming a file the map has no row for, when checked, then the consistency rule fails", () => {
    const text = DRAFT.replace(
      "2. Keep the method the same on both sides. [fix 1]",
      "2. Add the changelog entry in \`db/schema.changelog.xml\`. [fix 1]",
    );
    expect(failedRules(checkSkillFormat(text, ext))).toContain("step-map-consistency");
  });

  it("given a step naming a file the map covers by pattern, when checked, then the row counts", () => {
    const text = DRAFT.replace(
      "1. Add the handler in \`controller/WidgetController.kt\`. [map 1]",
      "1. Add the handler in \`service/controller/OtherController.kt\`. [map 1]",
    );
    expect(failedRules(checkSkillFormat(text, ext))).not.toContain("step-map-consistency");
  });

  it("given a step with no citation, when checked, then the evidence rule fails", () => {
    const text = DRAFT.replace("2. Keep the method the same on both sides. [fix 1]", "2. Keep the method the same on both sides.");
    expect(failedRules(checkSkillFormat(text, ext))).toContain("step-evidence");
  });

  it("given a citation to a piece the evidence never carried, when checked, then the evidence rule fails", () => {
    const text = DRAFT.replace("[map 3]", "[map 9]");
    const findings = checkSkillFormat(text, ext);
    expect(failedRules(findings)).toContain("step-evidence");
    expect(findings.find((f) => f.rule === "step-evidence")!.detail).toContain("map 9");
  });

  it("given the share form the map itself uses, when checked, then the citation still resolves", () => {
    const text = DRAFT.replace("[map 3]", "[map 3/9]");
    expect(failedRules(checkSkillFormat(text, ext))).not.toContain("step-evidence");
  });

  it("given a draft with no packet behind it, when checked, then citations are not demanded", () => {
    const text = DRAFT.replace(/ \[(map|fix) \d+\]/g, "");
    const rules = failedRules(checkSkillFormat(text, { ...options, extended: true, expects: { fileMap: true, multiRepo: true } }));
    expect(rules).not.toContain("step-evidence");
  });

  it("given the unnumbered not-visible section, when steps are counted, then its bullets are not steps", () => {
    const text = DRAFT.replace(
      "- Whether the gateway needs a new rate class is recorded in no commit.",
      "- Whether the gateway needs a new rate class is recorded in no commit.\n- Whether a second gateway copy exists is recorded in no commit.",
    );
    expect(failedRules(checkSkillFormat(text, ext))).toEqual([]);
  });

  describe.each(dump.mustPass)("a hand-written skill is untouched by them: $label", ({ text }) => {
    it("given no packet and no map, when checked with the structural rules on, then nothing fails", () => {
      expect(failedRules(checkSkillFormat(text, { ...options, extended: true }))).toEqual([]);
    });
  });

  it("given the empty template, when checked with the structural rules on, then it is still rejected", () => {
    const skeleton = dump.broken.find((b) => b.label === "skeleton-empty")!.text;
    expect(formatPasses(checkSkillFormat(skeleton, ext))).toBe(false);
  });
});
